# Generated by Django 5.2.15 on 2026-06-24 03:20

from django.db import migrations


def backfill_profile_cover_letters(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    CoverLetter = apps.get_model('analysis', 'CoverLetter')
    records = []
    for profile in Profile.objects.exclude(cover_letters=[]).select_related('user'):
        for item in profile.cover_letters or []:
            question = str(item.get('question', '')).strip() if isinstance(item, dict) else ''
            answer = str(item.get('answer', '')).strip() if isinstance(item, dict) else str(item).strip()
            content = "\n".join(part for part in [f"Q. {question}" if question else '', f"A. {answer}" if answer else ''] if part)
            if content:
                records.append(CoverLetter(user_id=profile.user_id, content=content))
    if records:
        CoverLetter.objects.bulk_create(records)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analysis', '0006_analysis_company_analysis_job_posting_coverletter_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_profile_cover_letters, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='cover_letters',
        ),
    ]
