# Generated by Django 6.0.6 on 2026-06-05 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_posting_url', models.URLField()),
                ('submitted_cover_letter', models.TextField(blank=True)),
                ('selected_interview_types', models.JSONField(default=list)),
                ('text_roadmap', models.TextField(blank=True)),
                ('timeline_data', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '대기'), ('done', '완료'), ('failed', '실패')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='companies.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
