# Generated by Django 6.0.6 on 2026-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_competency_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='job_posting_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
