HTTP/1.1 200 OK
Date: Wed, 24 Jun 2026 03:25:01 GMT
Server: WSGIServer/0.2 CPython/3.11.9
Content-Type: application/json
Vary: Accept, origin
Allow: POST, OPTIONS
X-Frame-Options: DENY
Content-Length: 491
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

{"access":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyMjc4NzAxLCJpYXQiOjE3ODIyNzE1MDEsImp0aSI6ImEwYzA2NTYwNTJmMjRhNDY4MWZmYzgyY2IxZmJjZWJlIiwidXNlcl9pZCI6IjEyIn0.ynSSIPMpu4ob6bxDaQiQ5fPI-KQVLDH9zXTqRZpuRAc","refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mjg3NjMwMSwiaWF0IjoxNzgyMjcxNTAxLCJqdGkiOiJkMmZmZjEyOTM0OWM0NTExOGNmOWNjZWIxNDgyMTM5YiIsInVzZXJfaWQiOiIxMiJ9.-tR5x3YT5dSAJ4hTEmI4S0yLxBiTwUdPJFrQ47RtsA8"}
