HTTP/1.1 200 OK
Date: Wed, 24 Jun 2026 03:25:02 GMT
Server: WSGIServer/0.2 CPython/3.11.9
Content-Type: application/json
Vary: Accept, origin
Allow: GET, PUT, HEAD, OPTIONS
X-Frame-Options: DENY
Content-Length: 142
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

{"name":"","major":"","education":"","careers":[],"projects":[],"awards":[],"certificates":[],"updated_at":"2026-06-24T12:25:01.183610+09:00"}
