HTTP/1.1 200 OK
Date: Wed, 24 Jun 2026 03:23:34 GMT
Server: WSGIServer/0.2 CPython/3.11.9
Content-Type: application/json
Vary: Accept, origin
Allow: POST, OPTIONS
X-Frame-Options: DENY
Content-Length: 491
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

{"access":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyMjc4NjE0LCJpYXQiOjE3ODIyNzE0MTQsImp0aSI6ImJlMTllNmU5ZjdkZDQzMWJhZTQ5MTViOWM1OWIxZTQxIiwidXNlcl9pZCI6IjEwIn0.eB-ik-Rle8CLhV1a_3BqFCTSFuebCUhKP1GzH1emQxo","refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mjg3NjIxNCwiaWF0IjoxNzgyMjcxNDE0LCJqdGkiOiI2Y2E3MzQ3YTg4ZDU0NjUzYjYzZWNhOTQ5NzBlNWUyMCIsInVzZXJfaWQiOiIxMCJ9.o9q-uS61dkUVKhDR4So_HW-S1jWeAWYVmxXXK1jrDJU"}
