HTTP/1.1 201 Created
Date: Wed, 24 Jun 2026 03:25:01 GMT
Server: WSGIServer/0.2 CPython/3.11.9
Content-Type: application/json
Vary: Accept, origin
Allow: POST, OPTIONS
X-Frame-Options: DENY
Content-Length: 491
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin

{"access":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyMjc4NzAxLCJpYXQiOjE3ODIyNzE1MDEsImp0aSI6ImM2YThjZjVmMTk5OTRkZDRiOThkZWM0NjRhNGYyZTRiIiwidXNlcl9pZCI6IjEyIn0.GTV1HVp2dQRkOrEgs_IS8WI52w_uG6ZLTaDNT3TzsWk","refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mjg3NjMwMSwiaWF0IjoxNzgyMjcxNTAxLCJqdGkiOiI2MDEyMzg1NmJlOWY0M2Y4YjhjMDYxNWRjNmQ1ZDU2OCIsInVzZXJfaWQiOiIxMiJ9.vgow1EKy_Pu7JqC4JmFgudxC7P6xa8s3ZysktpQvWOY"}
