# Generated by Django 6.0.6 on 2026-06-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('large', '대기업'), ('mid', '중견기업'), ('startup', '스타트업')], default='large', max_length=20)),
                ('talent_description', models.TextField(blank=True)),
                ('culture_keywords', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('annual_salary_krw', models.BigIntegerField(default=0)),
                ('required_experience_years', models.IntegerField(default=0)),
                ('applicant_count', models.IntegerField(default=0)),
                ('interview_stages', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('job_description', models.TextField(blank=True)),
                ('preferred_qualifications', models.JSONField(default=list)),
                ('recommended_study_areas', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
