# Generated by Django 5.2.15 on 2026-06-24 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_roadmap_supported'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'interview_types',
            },
        ),
        migrations.CreateModel(
            name='RoleFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_families',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('database', 'Database'), ('infra', 'Infra'), ('cs', 'Computer science'), ('soft_skill', 'Soft skill'), ('domain', 'Domain')], max_length=50)),
                ('aliases', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'study_areas',
            },
        ),
        migrations.CreateModel(
            name='CompanySourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('fixture', 'Fixture'), ('admin_manual', 'Admin manual'), ('homepage', 'Homepage'), ('news', 'News'), ('blog', 'Blog'), ('public_report', 'Public report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='companies.company')),
            ],
            options={
                'db_table': 'company_source_documents',
            },
        ),
        migrations.CreateModel(
            name='CompanyKnowledgeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('business_area', 'Business area'), ('product', 'Product'), ('recent_issue', 'Recent issue'), ('talent_trait', 'Talent trait'), ('culture_keyword', 'Culture keyword'), ('tech_stack', 'Tech stack'), ('role_candidate', 'Role candidate'), ('skill_relation', 'Skill relation')], max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('predicate', models.CharField(max_length=100)),
                ('object', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('trust_level', models.CharField(choices=[('public_source', 'Public source'), ('admin_curated', 'Admin curated'), ('user_private_candidate', 'User private candidate')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_claims', to='companies.company')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_knowledge_claims', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_claims', to='companies.companysourcedocument')),
            ],
            options={
                'db_table': 'company_knowledge_claims',
            },
        ),
        migrations.CreateModel(
            name='CompanySourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('embedding_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='not_required', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='companies.companysourcedocument')),
            ],
            options={
                'db_table': 'company_source_chunks',
                'unique_together': {('source_document', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='CompanyKnowledgeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('predicate', models.CharField(max_length=100)),
                ('object', models.TextField()),
                ('trust_level', models.CharField(choices=[('public_source', 'Public source'), ('admin_curated', 'Admin curated')], max_length=40)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('approved_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projected_facts', to='companies.companyknowledgeclaim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_facts', to='companies.company')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_facts', to='companies.companysourcedocument')),
            ],
            options={
                'db_table': 'company_knowledge_facts',
                'unique_together': {('company', 'fact_type', 'subject', 'predicate', 'object')},
            },
        ),
        migrations.CreateModel(
            name='RoleFamilySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('contextual', 'Contextual')], default='required', max_length=20)),
                ('role_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='companies.rolefamily')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_family_requirements', to='companies.skill')),
            ],
            options={
                'db_table': 'role_family_skills',
                'unique_together': {('role_family', 'skill')},
            },
        ),
    ]
