# Generated by Django 5.2.15 on 2026-06-24 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_interviewtype_rolefamily_skill_studyarea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyknowledgeclaim',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_knowledge_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
