# Generated by Django 5.2.15 on 2026-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companyknowledgeclaim_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysourcechunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysourcechunk',
            name='embedding_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companysourcechunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='companysourcechunk',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
